version: '3.1'

services:

  app:
    container_name: todo-list
    image: phreak1n/todo:latest
    restart: always
    ports:
      - "80:80"

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: todo
      MONGODB_INITDB_ROOT_PASSWORD: todosecret
      MONGODB_INITDB_DATABASE: todo

  mongo-express:
    container_name: monog-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: todo
      ME_CONFIG_MONGODB_ADMINPASSWORD: todosecret
